apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-identity-webhook
  namespace: default
spec:
  selector:
    matchLabels:
      app: pod-identity-webhook
  template:
    metadata:
      labels:
        app: pod-identity-webhook
    spec:
      serviceAccountName: pod-identity-webhook
      containers:
      - name: pod-identity-webhook
        image: err0r500/eks-pod-identity-webhook 
        imagePullPolicy: Always
        command:
        - /webhook
        - --in-cluster
        - --namespace=default
        - --service-name=pod-identity-webhook
        - --tls-secret=webhook-tls-cert
        - --annotation-prefix=eks.amazonaws.com
        - --token-audience=sts.amazonaws.com
        - --logtostderr
        - --enable-debugging-handlers
        volumeMounts:
        - name: webhook-certs
          mountPath: /var/run/app/certs
          readOnly: false
      volumes:
      - name: webhook-certs
        emptyDir: {}
