# permissions for end users to view iamroleserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iamroleserviceaccount-viewer-role
rules:
- apiGroups:
  - irsa.voodoo.io
  resources:
  - iamroleserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - irsa.voodoo.io
  resources:
  - iamroleserviceaccounts/status
  verbs:
  - get
