apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iamroleserviceaccounts.irsa.voodoo.io
spec:
  group: irsa.voodoo.io
  names:
    kind: IamRoleServiceAccount
    listKind: IamRoleServiceAccountList
    plural: iamroleserviceaccounts
    singular: iamroleserviceaccount
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: IamRoleServiceAccount is the Schema for the iamroleserviceaccounts API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: IamRoleServiceAccountSpec defines the desired state of IamRoleServiceAccount
              properties:
                policy:
                  description: PolicySpec describes the policy that must be present on AWS
                  properties:
                    arn:
                      type: string
                    statement:
                      items:
                        description: StatementSpec defines an aws statement (Sid is autogenerated & Effect is always "allow")
                        properties:
                          action:
                            items:
                              type: string
                            type: array
                          resource:
                            type: string
                        required:
                          - action
                          - resource
                        type: object
                      type: array
                  required:
                    - statement
                  type: object
              required:
                - policy
              type: object
            status:
              description: IamRoleServiceAccountStatus defines the observed state of IamRoleServiceAccount
              properties:
                condition:
                  type: string
                reason:
                  type: string
              required:
                - condition
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
