apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.irsa.voodoo.io
spec:
  group: irsa.voodoo.io
  names:
    kind: Policy
    listKind: PolicyList
    plural: policies
    singular: policy
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Policy is the Schema for the awspolicies API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: PolicySpec describes the policy that must be present on AWS
              properties:
                arn:
                  type: string
                statement:
                  items:
                    description: StatementSpec defines an aws statement (Sid is autogenerated & Effect is always "allow")
                    properties:
                      action:
                        items:
                          type: string
                        type: array
                      resource:
                        type: string
                    required:
                      - action
                      - resource
                    type: object
                  type: array
              required:
                - statement
              type: object
            status:
              description: PolicyStatus defines the observed state of Policy
              properties:
                condition:
                  description: poorman's golang enum
                  type: string
                reason:
                  type: string
              required:
                - condition
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
