---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irsa-operator.fullname" . }}-metrics
  labels:
    {{- include "irsa-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "irsa-operator.selectorLabels" . | nindent 4 }}
