{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "irsa-operator.serviceAccountName" . }}
  labels:
    {{- include "irsa-operator.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "roleARN is required, used to grant irsa-operator the right to create IAM resources" .Values.roleARN }}
    {{- range $key, $val := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
{{- end }}
